### ISSUE TITLE
breaks copy password/username

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-otp#1]
The current behavior:

> The code in the clipboard doesn't yet refresh - if you need a new code, you must invoke the Browserpass entry again.

breaks copy password/username buttons

**Comment by erayd** [comment]
Thanks for reporting this. The problem will likely go away once this extension gains a UI; the immediately-pushing-to-clipboard thing is temporary.

**Comment by erayd** [comment]
Fixed in #6.
