### ISSUE TITLE
16px icon

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-otp#10]
The current one:
![image](https://user-images.githubusercontent.com/14617699/64067440-323f8c00-cc31-11e9-888b-6c1d3fa66646.png)

my corrections:
![image](https://user-images.githubusercontent.com/14617699/64067434-1a680800-cc31-11e9-84df-a2d0bd966f88.png)

![image](https://user-images.githubusercontent.com/14617699/64067431-0e7c4600-cc31-11e9-82de-357ab75a9578.png)

**Comment by erayd** [comment]
Added in #11 - thanks :+1:

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/64854194-b75d7480-d625-11e9-8b3d-7d70907f7d84.png)
![image](https://user-images.githubusercontent.com/14617699/64854220-c5ab9080-d625-11e9-89d2-32f79602e0ec.png)

**Comment by 532910** [comment]
Any update?

**Comment by erayd** [comment]
Sorry, I lost sight of this one. They look fine :-). Will try to get them added this weekend.
