### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by webcoderkz** [browserpass/browserpass-otp#18]
I see no README there, could you add a documentation for this extension?

**Comment by apiraino** [comment]
As a starting point you can have a look at the brief README on the Mozilla addons site

https://addons.mozilla.org/de/firefox/addon/browserpass-otp

but a quick README is a good idea. @erayd is you want I can open a quick PR pasting the addon description on AMO :)

**Comment by webcoderkz** [comment]
My bad, it's available in a chrome web store :)

**Comment by erayd** [comment]
> I see no README there, could you add a documentation for this extension?

The documentation is in the chrome & firefox webstores, but you make a good point - it was missing here. I have now added it.
