### ISSUE TITLE
Firefox Add-on: follow-up on review request

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-otp#19]
@erayd will you be able to take care of this?

> Hello,
> 
> Hubert, a reviewer at addons.mozilla.org, found an issue when reviewing version 0.2.3 of the add-on Browserpass OTP and requests additional information. You are receiving this email because you are listed as an author of this add-on.
> 
> *********
> Hubert wrote:
> 
> Please provide us with build instructions for the source code, together with details about the dependencies.
> Test your build in a clean environment to make sure it is reproducible (node_module and build output folder cleaned).  
> We would also need your OS, node, npm or other building tools versions. 
> Please refer to this field (Provide build instructions) for more details: https://developer.mozilla.org/en-US/Add-ons/Source_Code_Submission
> 
> *********
> 
> To respond, please reply to this email or visit https://addons.mozilla.org/en-GB/developers/addon/browserpass-otp/versions. If we do not hear from you within seven (7) days of this notification, this listing may be removed from addons.mozilla.org.
> 
> Thank you for your attention.
> 
> -- 
> Mozilla Add-ons
> https://addons.mozilla.org
> 
> ===================================================================
> You received this email because you're subscribed to:
>    * email me when Mozilla needs to contact me about my individual add-on
> 
> 
> You can't unsubscribe from this type of email.
> 
> Manage email notifications: https://addons.mozilla.org/users/edit#acct-notify
>

**Comment by erayd** [comment]
Yup, I'll deal with it. Seems odd though, considering that this release contained exactly the same build instructions as every other version of this we have released.

**Comment by erayd** [comment]
Done - I've added `BUILDING.md` here, and also provided the contents of that file to the AMO reviewer.

**Comment by maximbaz** [comment]
Thank you!
