### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass-otp#24]
Hi,

I've just seen that this extension is being deprecated in favor of a similar feature in the main extension itself. Would you mind sharing a link where this was discussed/announced? I can't find it and I'm interested in the discussion.

Thank you very much for your extension!

**Comment by max-baz** [comment]
Hi, as you might know this topic was brought up several times, to get up to speed start reading from this comment onwards 😄 

https://github.com/browserpass/browserpass-otp/issues/17#issuecomment-650770802

Implementation PR: https://github.com/browserpass/browserpass-extension/pull/229

New release is planned on Thursday 17th

**Comment by DamienCassou** [comment]
You guys are just awesome!

Thank you for the quick answer.
