### ISSUE TITLE
Options screen requirements

### ISSUE THREAD

**Issue by erayd** [browserpass/browserpass-otp#8]
- Automatically copy OTP to clipboard when Browserpass is triggered (default to off)
 - Timeout period after which the extension should forget the OTP secret.

Until the options screen is implemented, auto-copy is set to on (except when Browserpass is using the clipboard), and the timeout is infinity, but the OTP secret will be forgotten when the tab is closed.

**Comment by DamienCassou** [comment]
> Timeout period after which the extension should forget the OTP secret.

is that really important? OTP passwords can only be used once and have a built-in timeout after which they can't be used anymore.

**Comment by erayd** [comment]
@DamienCassou I'm talking about the secret (which is used to generate the tokens), not the tokens (which are used to log in).

**Comment by erayd** [comment]
@maximbaz Given that the current implementation has been in use for over a year with no complaints, I'm thinking that an options screen may not actually be necessary. Thoughts?

**Comment by maximbaz** [comment]
Agree 👍 We can always revisit this if people come with ideas
