### ISSUE TITLE
Compile instructions?

### ISSUE THREAD

**Issue by apiraino** [browserpass/browserpass-otp#9]
Hi, I was trying to build the extension and sign it (with my Firefox account key) to test it easily on my local browser.

How ever `make firefox` returns an error:
```
$ make firefox
make -C src
make[1]: Entering directory '/home/user/browserpass-otp/src'
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
make[1]: *** [Makefile:13: deps] Error 1
make[1]: Leaving directory '/home/user/browserpass-otp/src'
make: *** [Makefile:14: extension] Error 2
```

I don't understand what am I missing, any hint? :-)

thanks!

**Comment by erayd** [comment]
That should work fine. Are you able to post every step you are taking (from the initial git clone), so that I can try to replicate your issue? As far as I can see, the build process is working correctly.

**Comment by apiraino** [comment]
- git clone the repo && cd into it
- `$ make firefox`

I tried figuring out that `install` error. If I touch a `src/install` file, then the error changes into:
```
$ make firefox
make -C src
make[1]: Entering directory '/home/user/browserpass-otp/src'
yarn install
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
make[1]: *** [Makefile:13: deps] Error 1
make[1]: Leaving directory '/home/user/browserpass-otp/src'
make: *** [Makefile:14: extension] Error 2
```

So I DDG'ed the error a bit and found [this on S.O.](https://stackoverflow.com/a/53471064) 

I was using the stock version (ubuntu 19.04) of `yarn` which apparently is broken (installed with `apt install cmdtest`).
```
$ yarn --version
0.32+git
```
now I have:
```
$ yarn --version
1.17.3
```

and now everything seems fine, now I have a `firefox` directory with all the files.

go figure -_-

**Comment by erayd** [comment]
@apiraino Really glad to hear you got it sorted :-).

That's good to know about Ubuntu also - it's such a major distro that sooner or later, somebody else is bound to run into the same problem. Neither I nor @maximbaz use Ubuntu, so it's unlikely we would have noticed it ourselves.

**Comment by apiraino** [comment]
@erayd can you release also a signed version of this extension?

**Comment by erayd** [comment]
@apiraino I already have; all releases are signed. Was there something you need that's missing from the release?

**Comment by apiraino** [comment]
Uhm ... I tried installing the `browserpass-otp-firefox-0.2.1-dev.zip` and Firefox (69.0b5) warns that that's an unsigned package. Which file should I exactly download for Firefox? Sorry for bothering.

**Comment by erayd** [comment]
@apiraino The signed Firefox package is available in the official add-ons store: https://addons.mozilla.org/en-US/firefox/addon/browserpass-otp/

The Firefox package must be signed by Mozilla, unfortunately with a key that I don't have. Alternatively, you can use the 'load temporary add-on' option at `about:debugging` to load the unsigned package.

Chrome doesn't have the same issue; the GitHub release includes a package signed with the webstore release key, and also one signed with a GitHub-only key if you wish to prevent chrome from auto-updating it.

**Comment by apiraino** [comment]
oh my bad. The extension is *already* published on the store. for some reason I gave for granted the opposite. sorry again. thanks
